### ISSUE TITLE
Dependency cannot find package.json 

### ISSUE THREAD

**Issue by Saltallica** [compiiile/compiiile#22]
Trying to get things up and running.

(Local project install, not global)

Node v20.10.0

package.json

```json
{

  "scripts": {
		"dev": "compiiile dev",
		"build": "compiiile build",
		"preview": "compiiile preview"
	},
  "dependencies": {
    "compiiile": "^2.1.5"
  }
}
```

Folder structure:

![image](https://github.com/compiiile/compiiile/assets/1064853/ccc78895-27cb-4b8d-a488-464a19734c0a)

running dev or build  script results in the following:

```
PS C:\projects\ad-docs> yarn run dev
yarn run v1.22.21
warning package.json: No license field
$ compiiile dev
file:///C:/projects/ad-docs/node_modules/vitefu/src/index.js:33
      throw new Error(`Cannot find package.json from ${options.root}`)
            ^

Error: Cannot find package.json from C:\C:\projects\ad-docs\node_modules\compiiile\.compiiile\
    at crawlFrameworkPkgs (file:///C:/projects/ad-docs/node_modules/vitefu/src/index.js:33:13)
    at async createVite (file:///C:/projects/ad-docs/node_modules/astro/dist/core/create-vite.js:51:27)
    at async createContainer (file:///C:/projects/ad-docs/node_modules/astro/dist/core/dev/container.js:33:22)
    at async createContainerWithAutomaticRestart (file:///C:/projects/ad-docs/node_modules/astro/dist/core/dev/restart.js:74:28)
    at async dev (file:///C:/projects/ad-docs/node_modules/astro/dist/core/dev/dev.js:11:19)
    at async file:///C:/projects/ad-docs/node_modules/compiiile/bin/cli.js:121:2

Node.js v20.10.0
error Command failed with exit code 1.
```

running preview script:

```
PS C:\projects\ad-docs> yarn run preview
yarn run v1.22.21
warning package.json: No license field
$ compiiile preview
   astro  v3.6.4 started in 9ms

  ┃ Local    http://localhost:4321/
  ┃ Network  use --host to expose
```

Brings up preview.. with a big 404...

![image](https://github.com/compiiile/compiiile/assets/1064853/02d7321d-42ec-4887-af5d-c82b74784cc7)

Assuming there is other initial setup, folder creation that is required by a dependency?

**Comment by AlbanCrepel** [comment]
Can you try using the latest version of the package ? (`@compiiile/compiiile` `2.2.1` ; no src directory is required btw)

If it's still not working, I'll reproduce it and have a look at this specific issue. From what I can see it's supposed to be working without further configuration.

**Comment by AlbanCrepel** [comment]
Did you manage to get things working @Saltallica ? If not, don't hesitate to reach out, I'll help. Otherwise if there is no new activity on this issue, I'll close it.

**Comment by rektdeckard** [comment]
Hi @AlbanCrepel, I'm experiencing the same thing with a global install of compiiile (via NPM). I have tried monkey-patching this method in the `vitefu` script to return its default value, but there seem to be cascading errors related to Windows file paths. Possible this is an Astro thing?

**Comment by AlbanCrepel** [comment]
Hey @rektdeckard, I am not experiencing this issue with a global npm install. 
- Are there any spaces in the full path ?
- Which version of the package are you using ?
- Could you please provide a **reproduction** ? At least the complete error log ?

**Comment by rektdeckard** [comment]
I have no spaces in either the path of my project or the global NPM install location where the error is thrown, and I am using `@compiiile/compiiile@2.10.0`.

To repro on Windows 11, Node v20.12.0:

1. `npm install -g @compiiile/compiiile`
2. Follow [Quick start](https://compiiile.me/#quick-start) instructions, generating a new project directory with `README.md` and `slides.md`
3. Run `compiiile`

```cmd
C:\Users\fried\Desktop\test-compiiile>compiiile --version
2.10.0

C:\Users\fried\Desktop\test-compiiile>dir
 Volume in drive C has no label.
 Volume Serial Number is 8299-C4C9

 Directory of C:\Users\fried\Desktop\test-compiiile

04/11/2024  02:11 AM    <DIR>          .
04/10/2024  09:10 PM    <DIR>          ..
04/10/2024  04:48 PM                85 README.md
04/10/2024  04:49 PM                71 slides.md
               2 File(s)            156 bytes
               2 Dir(s)  378,067,017,728 bytes free

C:\Users\fried\Desktop\test-compiiile>compiiile
file:///C:/Users/fried/AppData/Roaming/npm/node_modules/@compiiile/compiiile/node_modules/vitefu/src/index.js:33
      throw new Error(`Cannot find package.json from ${options.root}`)
            ^

Error: Cannot find package.json from C:\C:\Users\fried\AppData\Roaming\npm\node_modules\@compiiile\compiiile\.compiiile\
    at crawlFrameworkPkgs (file:///C:/Users/fried/AppData/Roaming/npm/node_modules/@compiiile/compiiile/node_modules/vitefu/src/index.js:33:13)
    at async createVite (file:///C:/Users/fried/AppData/Roaming/npm/node_modules/@compiiile/compiiile/node_modules/astro/dist/core/create-vite.js:53:27)
    at async createContainer (file:///C:/Users/fried/AppData/Roaming/npm/node_modules/@compiiile/compiiile/node_modules/astro/dist/core/dev/container.js:33:22)
    at async createContainerWithAutomaticRestart (file:///C:/Users/fried/AppData/Roaming/npm/node_modules/@compiiile/compiiile/node_modules/astro/dist/core/dev/restart.js:77:28)
    at async dev (file:///C:/Users/fried/AppData/Roaming/npm/node_modules/@compiiile/compiiile/node_modules/astro/dist/core/dev/dev.js:14:19)
    at async run (file:///C:/Users/fried/AppData/Roaming/npm/node_modules/@compiiile/compiiile/bin/config.js:215:21)
    at async file:///C:/Users/fried/AppData/Roaming/npm/node_modules/@compiiile/compiiile/bin/cli.js:4:1

Node.js v20.12.0
```

**Comment by AlbanCrepel** [comment]
Thanks a lot for these details 🙏  I'll investigate and come back to you. It seems that the error comes from the duplicated `C:\` part in `Cannot find package.json from `C:\C:\Users.....`.

**Comment by rektdeckard** [comment]
FWIW, I tried adding some logging in there, and my `options.root` value is `C:\\C:\\Users\\fried\\AppData\\Roaming\\npm\\node_modules\\@compiiile\\compiiile\\.compiiile\\`, with the disk label repeated.

EDIT: oops, just saw your reply. Yep, that's suspicious.

**Comment by rektdeckard** [comment]
I think it is these lines:

https://github.com/compiiile/compiiile/blob/dev/bin/config.js#L148-L149

Which should use [URL.fileURLToPath(url)](https://nodejs.org/dist/latest-v10.x/docs/api/url.html#url_url_fileurltopath_url), which ensures valid absolute paths in a cross-platform manner. See https://github.com/nodejs/node/issues/24223

**Comment by AlbanCrepel** [comment]
@rektdeckard I merged your PR and I will keep investigating for Windows-specific errors 👀

**Comment by AlbanCrepel** [comment]
@rektdeckard When I tested the code merged it did not work, giving the same 404 error Saltallica got earlier, on my MacOS. So I fixed the lines you modified. You can still try the fix in the `2.10.1` version.

**Comment by rektdeckard** [comment]
@AlbanCrepel I'll try something else. Can test on my linux machine to make sure it works with POSIX paths.

**Comment by AlbanCrepel** [comment]
Hey @rektdeckard @Saltallica, I fixed the global install to work on Windows systems, I tried it with the latest version (`2.10.2`). Make sure to update your package version and it should now work :tada: (I only normalized paths to work on both Windows using `\` and UNIX systems using `/`)

**Comment by rektdeckard** [comment]
Awesome. It's working OK when the source folder is on the same disk, but still experiencing errors when the source folder is on a different drive than the `compiiile` install. I'll open a separate issue.

**Comment by AlbanCrepel** [comment]
@rektdeckard I might be wrong but I guess this is an issue with your local config then. Is it specific to Compiiile or does it behave the same with other packages ? 

When installing a package globally (`npm i -g`), it install packages in specific folders, where `npm` itself is installed. You might have to set environment variables to point to the install folder. I am not on Windows myself but I searched this issue on the Internet and found a few links that can help you:
- https://stackoverflow.com/questions/9587665/nodejs-cannot-find-installed-module-on-windows
- https://stackoverflow.com/questions/19874582/change-default-global-installation-directory-for-node-js-modules-in-windows
- https://docs.npmjs.com/cli/v7/configuring-npm/folders

Let me know if this helped.

**Comment by rektdeckard** [comment]
It's specific to compiiile. Again, it's to do with mangled paths that I suspect are due to several places where paths are built by string concatenation or templating, rather than using the `node:path` helpers. Will document and submit the issue later tonight.
